Feature: Allow drop folder(s)
TeamWertarbyte/material-ui-file-dropzone pull request #2
Opened 2020-09-22 14:01 UTC by nithins

This feature allows the DropAreaBase to accept folders as well. Folder(s) will be recursively scanned and the files within will be collected into a flat array. The file array is passed on to `onSelectFiles`

2020-09-22 16:45 UTC, leMaik commented
Wow, that was quick! Thank you, @nithins :tada:

2020-09-22 16:51 UTC, leMaik requested changes

2020-09-22 16:51 UTC, leMaik commented on src/DropAreaBase/DropAreaBase.js
> +        .all([...e.dataTransfer.items].map(item => recurseItem(item.webkitGetAsEntry(), '/')))
What if `item.webkitGetAsEntry` is `undefined` here? Wouldn't it be better to fall back to `e.dataTransfer.files` in that case?

2020-09-22 16:51 UTC, leMaik commented on src/DropAreaBase/DropAreaBase.js
> +        if (item.isFile) { resolve([await new Promise((resolve, reject) => item.file(resolve, reject))]) }
To get rid of the nested promise constructor and the weird `reject` inside `resolve` (probably leading to unhandled promise rejection?), this could be changed to something like this:

```js
if (item.isFile) {
  item.file((singleFile) => resolve([singleFile]), (e) => reject(e));
}
```

2020-09-22 16:51 UTC, leMaik commented on src/DropAreaBase/DropAreaBase.js
> +          item.createReader().readEntries(async entries =>
`async` is only required when using `await` in the function body.

2020-09-23 07:18 UTC, nithins commented
Thanks for the review @leMaik . I've incorporated all the changes. 

The only change that feels iffy is on how to check if webkitGetAsEntry API is supported. Currently, the items[0] is being checked . There could be a better way. Please let me know if you can think of anything.

2020-09-23 15:54 UTC, leMaik commented
@nithins Thank you! :clap: 

You could detect support outside of the handler like this: `const folderDropSupported = 'webkitGetAsEntry' in DataTransferItem.prototype`

2020-09-24 16:38 UTC, leMaik approved these changes

2020-09-30 09:19 UTC, nithins commented
Hi @leMaik . I have completed and checked in the changes on the fork. I'm not sure of how to merge pull requests. Please let me know if there is anything I need to do. Also, I could squash the changes to maintain a single commit before you merge the pull request.

2020-10-19 14:30 UTC, merged

2020-10-19 14:31 UTC, leMaik commented
@nithins Sorry, this went off my radar :grimacing: I'm publishing a new release right now, thanks again for your work! :tada:

2020-10-21 02:45 UTC, nithins commented
@LeMaik.  Thanks for letting me know. Happy to contribute.


On Mon, 19 Oct 2020 at 20:01, Maik Marschner <notifications@github.com>
wrote:

> @nithins <https://github.com/nithins> Sorry, this went off my radar 😬
> I'm publishing a new release right now, thanks again for your work! 🎉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TeamWertarbyte/material-ui-file-dropzone/pull/2#issuecomment-712202340>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABQ2SSQWR7VX4A3UKAJTJTSLREVLANCNFSM4RV2CRUQ>
> .
>